import "hard-rejection/register"
import "./mocha.js"
import resetState from "./reset-state.js"

import "./builtin-modules.mjs"
import "./cache-tests.js"
import "./cli-hook-tests.mjs"
import "./compiler-tests.mjs"
import "./dynamic-import-tests.mjs"
import "./eval-hook-tests.mjs"
import "./export-tests.mjs"
import "./file-extension-tests.js"
import "./import-tests.js"
import "./main-hook-tests.mjs"
import "./misc-tests.js"
import "./output-tests.mjs"
import "./setter-tests.js"
import "./top-level-await-tests.js"
import "./url-tests.mjs"
import "./wasm-tests.js"
import "./require-hook-tests.js"
import "./scenario-tests.mjs"

// import "./check-hook-tests.mjs"
// import "./repl-hook-tests.mjs"
// import "./test262.mjs"

beforeEach(resetState)
