allowBuilds:
  '@datadog/pprof': false
  '@newrelic/fn-inspect': false
  '@newrelic/native-metrics': false
  core-js: false
  ejs: false
  fsevents: false
  husky: true
  protobufjs: false
  sleep: false
  sq-native: false
  unrs-resolver: false
